--------------------------------------------------------------------------------
--  File:   lqr_block.vhd
--  Desc:   PandABlocks framework adapter around lqr_top.
--  Author: richard.cunningham@diamond.ac.uk
--------------------------------------------------------------------------------

-- AUTOGENERATED -- configure with the Python generator, not this file.


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.matrix_consts.all;
use work.mac_utils.all;
use work.num_utils.all;
use work.lqr_consts.all;
use work.cond_consts.all;
use work.state_abi.all;


entity lqr_block is
    port (
        clk_i : in std_logic; -- PandA master clock
        init_i : in std_logic; -- PandA Reset

        pos0_i : in std_logic_vector(31 downto 0); -- [POS0] pos_mux
        pos1_i : in std_logic_vector(31 downto 0); -- [POS1] pos_mux
        pos2_i : in std_logic_vector(31 downto 0); -- [POS2] pos_mux
        SP0_i : in std_logic_vector(31 downto 0); -- [SP0] pos_mux
        SP1_i : in std_logic_vector(31 downto 0); -- [SP1] pos_mux
        SP2_i : in std_logic_vector(31 downto 0); -- [SP2] pos_mux
        SV0_i : in std_logic_vector(31 downto 0); -- [SV0] pos_mux
        SV1_i : in std_logic_vector(31 downto 0); -- [SV1] pos_mux
        SV2_i : in std_logic_vector(31 downto 0); -- [SV2] pos_mux

        -- Table short: words stream to DATA, no address on the bus
        GAINS_START : in std_logic_vector(31 downto 0);
        GAINS_START_WSTB : in std_logic;
        GAINS_DATA : in std_logic_vector(31 downto 0);
        GAINS_DATA_WSTB : in std_logic;
        GAINS_LENGTH : in std_logic_vector(31 downto 0); -- informational
        GAINS_LENGTH_WSTB : in std_logic;

        -- Param bit + wstb: pulse swaps the staged bank (value unused)
        COMMIT : in std_logic_vector(31 downto 0);
        COMMIT_WSTB : in std_logic;

        GEN : out std_logic_vector(31 downto 0); -- Read: generation tag

        u0_o : out std_logic_vector(31 downto 0); -- [U0] pos_out
        u1_o : out std_logic_vector(31 downto 0); -- [U1] pos_out
        u2_o : out std_logic_vector(31 downto 0); -- [U2] pos_out

        -- ACP write-master bundle (records thread one port per wrapper level)
        m_axi_o : out acp_mosi_t;
        m_axi_i : in acp_miso_t;

        u_valid_o : out std_logic
    );
end entity;


architecture main of lqr_block is
    -- Frozen build config
    constant AXES : positive := 3;
    constant M : positive := 3;
    constant DIV : positive := 12500; -- 125MHz / DIV
    constant HIST_DEPTH : positive := 2;
    constant INTER_SCALE : real := 0.256; -- 256pm / count -> nm
    constant G_PHI : natural := 0;
    constant G_REF : natural := 6; -- 2 orders x AXES
    constant G_VELOCITY : boolean := true;
    constant G_PREV : boolean := true;
    constant G_UPREV : boolean := true;
    constant G_SETPOINT : boolean := true;
    constant G_AFFINE : boolean := true;
    constant G_EXPORT : boolean := true;
    constant BASE_ADDR : std_logic_vector(31 downto 0) := x"3FFF0000";
    constant CHUNK : natural := 8;

    -- Derived
    constant N : positive := cond_width(AXES, true, G_VELOCITY, G_PREV);
    constant REF : positive := resolve_ref(N, G_REF);
    constant GAIN_CNT : positive := M * n_int(N, M, REF, G_PHI, G_UPREV, G_SETPOINT, G_AFFINE);
    constant GAIN_ADDR_W : positive := ceil_log2(GAIN_CNT);

    -- Signals
    signal pos_vec : mac_data_vec(0 to AXES - 1);
    signal sp_vec : mac_data_vec(0 to REF - 1);
    signal u_vec : lqr_out_vec(0 to M - 1);
    signal gen_u : unsigned(GEN_W - 1 downto 0);

    signal cnt : unsigned(GAIN_ADDR_W - 1 downto 0);
    signal wr_addr : unsigned(GAIN_ADDR_W - 1 downto 0);
    signal wr_data : signed(LANE_B_W - 1 downto 0);
    signal wr_en : std_logic;

    -- Gain-fill source seam
    signal fill_start : std_logic;
    signal fill_valid : std_logic;
    signal fill_data : std_logic_vector(31 downto 0);

begin

    -- State inputs: sign-extend pos bus (32b) -> lanes (42b)
    pos_vec(0) <= resize(signed(pos0_i), LANE_A_W);
    pos_vec(1) <= resize(signed(pos1_i), LANE_A_W);
    pos_vec(2) <= resize(signed(pos2_i), LANE_A_W);

    -- Setpoint demands: [order0 | order1 | ...], each AXES-wide slice
    sp_vec(0) <= resize(signed(SP0_i), LANE_A_W);
    sp_vec(1) <= resize(signed(SP1_i), LANE_A_W);
    sp_vec(2) <= resize(signed(SP2_i), LANE_A_W);
    sp_vec(3) <= resize(signed(SV0_i), LANE_A_W);
    sp_vec(4) <= resize(signed(SV1_i), LANE_A_W);
    sp_vec(5) <= resize(signed(SV2_i), LANE_A_W);

    -- Control outputs: sign-extend DAC (7b) -> pos bus (32b)
    u0_o <= std_logic_vector(resize(u_vec(0), 32));
    u1_o <= std_logic_vector(resize(u_vec(1), 32));
    u2_o <= std_logic_vector(resize(u_vec(2), 32));

    -- Generation tag: zero-extend (16b) -> readback reg (32b)
    GEN <= std_logic_vector(resize(gen_u, 32));

    -- Gain-fill source: register-burst stream
    fill_start <= GAINS_START_WSTB;
    fill_valid <= GAINS_DATA_WSTB;
    fill_data <= GAINS_DATA;

    -- Gain fill FSM: word-stream -> addressed BRAM write.
    -- start resets the pointer, each valid word writes then increments.
    process(clk_i) begin
        if rising_edge(clk_i) then
            wr_en <= '0'; -- strobe: default low, pulse per word

            if init_i = '1' or fill_start = '1' then
                cnt <= (others => '0');
            elsif fill_valid = '1' then
                wr_addr <= cnt;
                wr_data <= signed(fill_data);
                wr_en <= '1';
                cnt <= cnt + 1;
            end if;
        end if;
    end process;

    -- The controller
    u_lqr : entity work.lqr_top
        generic map (
            AXES => AXES,
            M => M,
            DIV => DIV,
            HIST_DEPTH => HIST_DEPTH,
            INTER_SCALE => INTER_SCALE,
            G_PHI => G_PHI,
            G_REF => G_REF,
            G_EXPORT => G_EXPORT,
            G_VELOCITY => G_VELOCITY,
            G_PREV => G_PREV,
            G_UPREV => G_UPREV,
            G_SETPOINT => G_SETPOINT,
            BASE_ADDR => BASE_ADDR,
            CHUNK => CHUNK,
            G_AFFINE => G_AFFINE
        )
        port map (
            clk_i => clk_i,
            init_i => init_i,
            pos_i => pos_vec,
            sp_i => sp_vec,
            wr_addr_i => wr_addr,
            wr_data_i => wr_data,
            wr_en_i => wr_en,
            commit_i => COMMIT_WSTB,
            gen_o => gen_u,
            u_o => u_vec,

            m_axi_awvalid => m_axi_o.awvalid,
            m_axi_awready => m_axi_i.awready,
            m_axi_awaddr => m_axi_o.awaddr,
            m_axi_awid => m_axi_o.awid,
            m_axi_awlen => m_axi_o.awlen,
            m_axi_awsize => m_axi_o.awsize,
            m_axi_awburst => m_axi_o.awburst,
            m_axi_awcache => m_axi_o.awcache,
            m_axi_awuser => m_axi_o.awuser,
            m_axi_awprot => m_axi_o.awprot,
            m_axi_awlock => m_axi_o.awlock,
            m_axi_awqos => m_axi_o.awqos,

            m_axi_wvalid => m_axi_o.wvalid,
            m_axi_wready => m_axi_i.wready,
            m_axi_wid => m_axi_o.wid,
            m_axi_wdata => m_axi_o.wdata,
            m_axi_wstrb => m_axi_o.wstrb,
            m_axi_wlast => m_axi_o.wlast,

            m_axi_bvalid => m_axi_i.bvalid,
            m_axi_bready => m_axi_o.bready,
            m_axi_bresp => m_axi_i.bresp,
            m_axi_bid => m_axi_i.bid,

            u_valid_o => u_valid_o
        );

end architecture main;
