--------------------------------------------------------------------------------
--  File:   lqr_block_dma.vhd
--  Desc:   PandABlocks framework adapter around lqr_top.
--  Author: richard.cunningham@diamond.ac.uk
--------------------------------------------------------------------------------

-- AUTOGENERATED -- configure with the Python generator, not this file.


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.matrix_consts.all;
use work.mac_utils.all;
use work.num_utils.all;
use work.lqr_consts.all;
use work.cond_consts.all;


entity lqr_block_dma is
    port (
        clk_i : in std_logic; -- PandA master clock
        init_i : in std_logic; -- PandA Reset

        pos0_i : in std_logic_vector(31 downto 0); -- [POS0] pos_mux
        pos1_i : in std_logic_vector(31 downto 0); -- [POS1] pos_mux
        pos2_i : in std_logic_vector(31 downto 0); -- [POS2] pos_mux
        sp0_i : in std_logic_vector(31 downto 0); -- [SP0] pos_mux
        sp1_i : in std_logic_vector(31 downto 0); -- [SP1] pos_mux
        sp2_i : in std_logic_vector(31 downto 0); -- [SP2] pos_mux

        -- Table (long): host writes ADDRESS + LENGTH, block masters the read
        GAINS_ADDRESS : in std_logic_vector(31 downto 0);
        GAINS_ADDRESS_WSTB : in std_logic;
        GAINS_LENGTH : in std_logic_vector(31 downto 0); -- bytes
        GAINS_LENGTH_WSTB : in std_logic;

        -- DMA master bundle (wrapper binds to read engine)
        dma_req_o : out std_logic;
        dma_ack_i : in std_logic;
        dma_done_i : in std_logic;
        dma_addr_o : out std_logic_vector(31 downto 0);
        dma_len_o : out std_logic_vector(7 downto 0); -- words
        dma_data_i : in std_logic_vector(31 downto 0);
        dma_valid_i : in std_logic;

        -- Param bit + wstb: pulse swaps the staged bank (value unused)
        COMMIT : in std_logic_vector(31 downto 0);
        COMMIT_WSTB : in std_logic;

        GEN : out std_logic_vector(31 downto 0); -- Read: generation tag

        u0_o : out std_logic_vector(31 downto 0); -- [U0] pos_out
        u1_o : out std_logic_vector(31 downto 0); -- [U1] pos_out
        u2_o : out std_logic_vector(31 downto 0); -- [U2] pos_out

        u_valid_o : out std_logic
    );
end entity;


architecture main of lqr_block_dma is
    -- Frozen build config
    constant AXES : positive := 3;
    constant M : positive := 3;
    constant DIV : positive := 12500; -- 125MHz / DIV
    constant HIST_DEPTH : positive := 2;
    constant INTER_SCALE : real := 0.256; -- 256pm / count -> nm
    constant G_PHI : natural := 0;
    constant G_VELOCITY : boolean := false;
    constant G_PREV : boolean := false;
    constant G_UPREV : boolean := true;
    constant G_SETPOINT : boolean := true;
    constant G_AFFINE : boolean := false;

    -- Derived
    constant N : positive := cond_width(AXES, true, G_VELOCITY, G_PREV);
    constant GAIN_CNT : positive := M * n_int(N, M, G_PHI, G_UPREV, G_SETPOINT, G_AFFINE);
    constant GAIN_ADDR_W : positive := ceil_log2(GAIN_CNT);

    -- Signals
    signal pos_vec : mac_data_vec(0 to AXES - 1);
    signal sp_vec : mac_data_vec(0 to N - 1);
    signal u_vec : lqr_out_vec(0 to M - 1);
    signal gen_u : unsigned(GEN_W - 1 downto 0);

    signal cnt : unsigned(GAIN_ADDR_W - 1 downto 0);
    signal wr_addr : unsigned(GAIN_ADDR_W - 1 downto 0);
    signal wr_data : signed(LANE_B_W - 1 downto 0);
    signal wr_en : std_logic;

    -- Gain-fill source seam
    signal fill_start : std_logic;
    signal fill_valid : std_logic;
    signal fill_data : std_logic_vector(31 downto 0);

    -- DMA request FSM
    type dma_state is (IDLE, REQ, STREAM, DONE);
    signal dma_fsm : dma_state;
    signal words : unsigned(31 downto 0); -- remaining dwords to fetch
    signal addr : unsigned(31 downto 0); -- byte address
    signal blen : unsigned(8 downto 0); -- this burst's length (words)

begin

    -- State inputs: sign-extend pos bus (32b) -> lanes (42b)
    pos_vec(0) <= resize(signed(pos0_i), LANE_A_W);
    pos_vec(1) <= resize(signed(pos1_i), LANE_A_W);
    pos_vec(2) <= resize(signed(pos2_i), LANE_A_W);

    -- Reference r(k): setpoint block (feedforward), or tied off when unused
    sp_vec(0) <= resize(signed(sp0_i), LANE_A_W);
    sp_vec(1) <= resize(signed(sp1_i), LANE_A_W);
    sp_vec(2) <= resize(signed(sp2_i), LANE_A_W);

    -- Control outputs: sign-extend DAC (7b) -> pos bus (32b)
    u0_o <= std_logic_vector(resize(u_vec(0), 32));
    u1_o <= std_logic_vector(resize(u_vec(1), 32));
    u2_o <= std_logic_vector(resize(u_vec(2), 32));

    -- Generation tag: zero-extend (16b) -> readback reg (32b)
    GEN <= std_logic_vector(resize(gen_u, 32));

    -- Gain-fill source: DMA stream (words land while STREAM)
    dma_addr_o <= std_logic_vector(addr);
    blen <= to_unsigned(256, blen'length) when words >= 256
            else words(8 downto 0);
    dma_len_o <= std_logic_vector(blen(7 downto 0));
    fill_valid <= dma_valid_i when dma_fsm = STREAM else '0';
    fill_data <= dma_data_i;

    -- 
    process(clk_i) begin
        if rising_edge(clk_i) then
            -- One-cycle pointer-reset pulse
            fill_start <= '0';

            if init_i = '1' then
                dma_fsm <= IDLE;
                dma_req_o <= '0';
                words <= (others => '0');
                addr <= (others => '0');
            else
                case dma_fsm is
                    when IDLE =>
                        dma_req_o <= '0';

                        if GAINS_LENGTH_WSTB = '1' and unsigned(GAINS_LENGTH) >= 4 then
                            words <= shift_right(unsigned(GAINS_LENGTH), 2); -- bytes -> dwords
                            addr <= unsigned(GAINS_ADDRESS);
                            fill_start <= '1'; -- reset the BRAM pointer for the load
                            dma_fsm <= REQ;
                        end if;

                    when REQ =>
                        dma_req_o <= '1'; -- addr + len already stable

                        -- Fire the DMA stream!
                        if dma_ack_i = '1' then
                            dma_req_o <= '0';
                            dma_fsm <= STREAM;
                        end if;

                    when STREAM =>
                        -- Words flow to the seam, advance on burst done
                        if dma_done_i = '1' then
                            words <= words - blen;
                            addr <= addr + shift_left(resize(blen, addr'length), 2);

                            if words - blen = 0 then
                                dma_fsm <= DONE;
                            else
                                dma_fsm <= REQ; -- next burst, pointer keeps counting
                            end if;
                        end if;

                    when DONE =>
                        dma_fsm <= IDLE; -- ready for the next load

                end case;
            end if;
        end if;
    end process;

    -- Gain fill FSM: word-stream -> addressed BRAM write.
    -- start resets the pointer, each valid word writes then increments.
    process(clk_i) begin
        if rising_edge(clk_i) then
            wr_en <= '0'; -- strobe: default low, pulse per word

            if init_i = '1' or fill_start = '1' then
                cnt <= (others => '0');
            elsif fill_valid = '1' then
                wr_addr <= cnt;
                wr_data <= signed(fill_data);
                wr_en <= '1';
                cnt <= cnt + 1;
            end if;
        end if;
    end process;

    -- The controller
    u_lqr : entity work.lqr_top
        generic map (
            AXES => AXES,
            M => M,
            DIV => DIV,
            HIST_DEPTH => HIST_DEPTH,
            INTER_SCALE => INTER_SCALE,
            G_PHI => G_PHI,
            G_VELOCITY => G_VELOCITY,
            G_PREV => G_PREV,
            G_UPREV => G_UPREV,
            G_SETPOINT => G_SETPOINT,
            G_AFFINE => G_AFFINE
        )
        port map (
            clk_i => clk_i,
            init_i => init_i,
            pos_i => pos_vec,
            sp_i => sp_vec,
            wr_addr_i => wr_addr,
            wr_data_i => wr_data,
            wr_en_i => wr_en,
            commit_i => COMMIT_WSTB,
            gen_o => gen_u,
            u_o => u_vec,
            u_valid_o => u_valid_o
        );

end architecture main;
