[.]
description: A Cascaded PID to control position and velocity.
entity: brett_pid

[INIT]
type: bit_mux
description: reset switch.

[PID_PERIOD_I]
type: param int
description: sets PID output rate as a function of the master clock.

[K_TOT_I]
type: param scalar
scale: 0.0000000009313225746154785
description: scale down total output.

[KP_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: position proportional constant.

[KV_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: velocity proportional constant.

[KI_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: integral proportional constant.

[KD_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: derivative proportional constant.

[KVFF_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: feedforward velocity constant.

[KAFF_I]
type: param scalar
scale: 0.00000095367431640625
description: feedforward acceleration constant.

[KPFF0_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: feedforward constant 0.

[KPFF1_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: feedforward constant 1.

[DO_VEL_DIFF_I]
type: param bit
description: use velocity instead of error in derivative calculation.

[DIR_TOGGLE_I]
type: param bit
description: output sign toggle.

[DT_I]
type: param scalar
; scale: 0.000000476837158203125
scale: 0.000000029802322387695312
description: sets dt for the integral term.

[DT_INV_I]
type: param scalar
scale: 0.001953125
description: sets 1/dt for the derivative term.

[MAX_INTEGRAL_I]
type: param int
description: a cap on integral growth.

[MAX_OUTPUT_I]
type: param int
description: a cap on PID output.

[REAL_INPUT]
type: pos_mux
description: process variable input to the PID.

[SETPOINT]
type: pos_mux
description: setpoint value for the PID.

[REAL_OUTPUT]
type: pos_out
description: final value output by the PID.