#!/usr/bin/env python3
"""
Generate lqr.block.ini + lqr_block.vhd for a chosen LQR/MPC controller shape.

Two ideas:
1. Derived sizes are computed with this script so the ini/wrapper and the 
    engine never drift out of sync.
2. The per-axis structure (#POS/SP inputs, #U outputs) is emitted with loops,
    the rest is fixed scaffolding.

We use jinja in PandABocks - Python 3.6 here for Diamond RedHat8 Machiones.

This file is largely AI generated!
"""

import argparse


class Config:
    def __init__(self, axes=3, m=3, div=12500, hist_depth=2, scale=0.256, g_phi=0,
                 g_velocity=True, g_prev=False, g_uprev=True,
                 g_setpoint=False, g_affine=False):
        self.axes = axes
        self.m = m
        self.div = div
        self.hist_depth = hist_depth
        self.scale = scale
        self.g_phi = g_phi
        self.g_velocity = g_velocity
        self.g_prev = g_prev
        self.g_uprev = g_uprev
        self.g_setpoint = g_setpoint
        self.g_affine = g_affine


# --- mirror the VHDL sizing functions (cond_consts.vhd / lqr_consts.vhd) ---

def n_channels(g_state, g_velocity, g_prev):
    return int(g_state) + int(g_velocity) + int(g_prev)


def cond_width(p, g_state, g_velocity, g_prev):
    return p * n_channels(g_state, g_velocity, g_prev)


def n_int(n, m, feats, uprev, setpoint, affine):
    return n + feats + m * int(uprev) + n * int(setpoint) + int(affine)


def state_width(c):
    # N: the conditioned state block width; also the setpoint width in today's engine.
    return cond_width(c.axes, True, c.g_velocity, c.g_prev)


def gain_count(c):
    return c.m * n_int(state_width(c), c.m, c.g_phi, c.g_uprev, c.g_setpoint, c.g_affine)


BANNER_INI = "# AUTOGENERATED -- configure with the Python generator, not this file"
BANNER_VHD = "-- AUTOGENERATED -- configure with the Python generator, not this file.\n"


def vbool(b):
    return "true" if b else "false"


def make_block_ini(c):
    out = [BANNER_INI, "", "[.]",
           "description: LQR / nonlinear state-feedback motion controller.",
           "entity: lqr_block", "",
           "[INIT]", "type: bit_mux",
           "description: Reset / re-initialise the controller."]

    for a in range(c.axes):                                   # state inputs
        out += ["", "[POS%d]" % a, "type: pos_mux",
                "description: Axis %d interferometer position (state input)." % a]

    if c.g_setpoint:                                          # reference r(k) inputs
        for i in range(state_width(c)):
            out += ["", "[SP%d]" % i, "type: pos_mux",
                    "description: Reference r(k) component %d (feedforward)." % i]

    out += ["", "[GAINS]", "type: table short", "words: 1",
            "lines: %d" % gain_count(c),
            "description: Flattened K matrix (row-major, Q7.25), "
            "streamed into the inactive gain bank.",
            "31:0 K int", "    One Q7.25 gain word.",
            "", "[COMMIT]", "type: param bit", "wstb: true",
            "description: Swap the staged gains into the active bank ",
            "", "[GEN]", "type: read",
            "description: Gain generation counter -- read to confirm a swap has landed."]

    for k in range(c.m):                                     # control outputs
        out += ["", "[U%d]" % k, "type: pos_out",
                "description: Axis %d control output to DAC." % k]

    out += ["", "[U_VALID]", "type: bit_out",
            "description: DAC latch strobe -- one pulse per completed control pass.", ""]
    return "\n".join(out)


def make_block_vhd(c):
    nsp = state_width(c) if c.g_setpoint else 0

    out = ["-" * 80,
        "--  File:   lqr_block.vhd",
        "--  Desc:   PandABlocks framework adapter around lqr_top.",
        "--  Author: richard.cunningham@diamond.ac.uk",
        "-" * 80, "",
        BANNER_VHD, "",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "use ieee.numeric_std.all;", "",
        "use work.matrix_consts.all;",
        "use work.mac_utils.all;",
        "use work.num_utils.all;",
        "use work.lqr_consts.all;",
        "use work.cond_consts.all;", "", "",
        "entity lqr_block is",
        "    port (",
        "        clk_i : in std_logic; -- PandA master clock",
        "        init_i : in std_logic; -- PandA Reset", ""]

    for a in range(c.axes):
        out.append("        pos%d_i : in std_logic_vector(31 downto 0); -- [POS%d] pos_mux" % (a, a))
    for i in range(nsp):
        out.append("        sp%d_i : in std_logic_vector(31 downto 0); -- [SP%d] pos_mux" % (i, i))

    out += ["",
        "        -- Table short: words stream to DATA, no address on the bus",
        "        GAINS_START : in std_logic_vector(31 downto 0);",
        "        GAINS_START_WSTB : in std_logic;",
        "        GAINS_DATA : in std_logic_vector(31 downto 0);",
        "        GAINS_DATA_WSTB : in std_logic;",
        "        GAINS_LENGTH : in std_logic_vector(31 downto 0); -- informational",
        "        GAINS_LENGTH_WSTB : in std_logic;", "",
        "        -- Param bit + wstb: pulse swaps the staged bank (value unused)",
        "        COMMIT : in std_logic_vector(31 downto 0);",
        "        COMMIT_WSTB : in std_logic;", "",
        "        GEN : out std_logic_vector(31 downto 0); -- Read: generation tag", ""]

    for k in range(c.m):
        out.append("        u%d_o : out std_logic_vector(31 downto 0); -- [U%d] pos_out" % (k, k))

    out += ["",
        "        u_valid_o : out std_logic",
        "    );",
        "end entity;", "", "",
        "architecture main of lqr_block is",
        "    -- Frozen build config",
        "    constant AXES : positive := %d;" % c.axes,
        "    constant M : positive := %d;" % c.m,
        "    constant DIV : positive := %d; -- 125MHz / DIV" % c.div,
        "    constant HIST_DEPTH : positive := %d;" % c.hist_depth,
        "    constant INTER_SCALE : real := %s; -- 256pm / count -> nm" % c.scale,
        "    constant G_PHI : natural := %d;" % c.g_phi,
        "    constant G_VELOCITY : boolean := %s;" % vbool(c.g_velocity),
        "    constant G_PREV : boolean := %s;" % vbool(c.g_prev),
        "    constant G_UPREV : boolean := %s;" % vbool(c.g_uprev),
        "    constant G_SETPOINT : boolean := %s;" % vbool(c.g_setpoint),
        "    constant G_AFFINE : boolean := %s;" % vbool(c.g_affine), "",
        "    -- Derived",
        "    constant N : positive := cond_width(AXES, true, G_VELOCITY, G_PREV);",
        "    constant GAIN_CNT : positive := M * n_int(N, M, G_PHI, G_UPREV, G_SETPOINT, G_AFFINE);",
        "    constant GAIN_ADDR_W : positive := ceil_log2(GAIN_CNT);", "",
        "    -- Signals",
        "    signal pos_vec : mac_data_vec(0 to AXES - 1);",
        "    signal sp_vec : mac_data_vec(0 to N - 1);",
        "    signal u_vec : lqr_out_vec(0 to M - 1);",
        "    signal gen_u : unsigned(GEN_W - 1 downto 0);", "",
        "    signal cnt : unsigned(GAIN_ADDR_W - 1 downto 0);",
        "    signal wr_addr : unsigned(GAIN_ADDR_W - 1 downto 0);",
        "    signal wr_data : signed(LANE_B_W - 1 downto 0);",
        "    signal wr_en : std_logic;", "",
        "    -- Gain-fill source seam",
        "    signal fill_start : std_logic;",
        "    signal fill_valid : std_logic;",
        "    signal fill_data : std_logic_vector(31 downto 0);", "",
        "begin", "",
        "    -- State inputs: sign-extend pos bus (32b) -> lanes (42b)"]

    for a in range(c.axes):
        out.append("    pos_vec(%d) <= resize(signed(pos%d_i), LANE_A_W);" % (a, a))

    out += ["", "    -- Reference r(k): setpoint block (feedforward), or tied off when unused"]
    if c.g_setpoint:
        for i in range(nsp):
            out.append("    sp_vec(%d) <= resize(signed(sp%d_i), LANE_A_W);" % (i, i))
    else:
        out.append("    sp_vec <= (others => (others => '0'));")

    out += ["", "    -- Control outputs: sign-extend DAC (7b) -> pos bus (32b)"]
    for k in range(c.m):
        out.append("    u%d_o <= std_logic_vector(resize(u_vec(%d), 32));" % (k, k))

    out += ["", "    -- Generation tag: zero-extend (16b) -> readback reg (32b)",
        "    GEN <= std_logic_vector(resize(gen_u, 32));", "",
        "    -- Gain-fill source: register-burst stream/DMA stream",
        "    fill_start <= GAINS_START_WSTB;",
        "    fill_valid <= GAINS_DATA_WSTB;",
        "    fill_data <= GAINS_DATA;", "",
        "    -- Gain fill FSM: word-stream -> addressed BRAM write.",
        "    -- start resets the pointer, each valid word writes then increments.",
        "    process(clk_i) begin",
        "        if rising_edge(clk_i) then",
        "            wr_en <= '0'; -- strobe: default low, pulse per word",
        "            if init_i = '1' or fill_start = '1' then",
        "                cnt <= (others => '0');",
        "            elsif fill_valid = '1' then",
        "                wr_addr <= cnt;",
        "                wr_data <= signed(fill_data);",
        "                wr_en <= '1';",
        "                cnt <= cnt + 1;",
        "            end if;",
        "        end if;",
        "    end process;", "",
        "    -- The controller",
        "    u_lqr : entity work.lqr_top",
        "        generic map (",
        "            AXES => AXES,",
        "            M => M,",
        "            DIV => DIV,",
        "            HIST_DEPTH => HIST_DEPTH,",
        "            INTER_SCALE => INTER_SCALE,",
        "            G_PHI => G_PHI,",
        "            G_VELOCITY => G_VELOCITY,",
        "            G_PREV => G_PREV,",
        "            G_UPREV => G_UPREV,",
        "            G_SETPOINT => G_SETPOINT,",
        "            G_AFFINE => G_AFFINE",
        "        )",
        "        port map (",
        "            clk_i => clk_i,",
        "            init_i => init_i,",
        "            pos_i => pos_vec,",
        "            sp_i => sp_vec,",
        "            wr_addr_i => wr_addr,",
        "            wr_data_i => wr_data,",
        "            wr_en_i => wr_en,",
        "            commit_i => COMMIT_WSTB,",
        "            gen_o => gen_u,",
        "            u_o => u_vec,",
        "            u_valid_o => u_valid_o",
        "        );", "",
        "end architecture main;", ""]
    return "\n".join(out)


def main():
    p = argparse.ArgumentParser(description="Generate the LQR PandA block for a given shape.")
    p.add_argument("--axes", type=int, default=3, help="number of state-axis inputs (POS*)")
    p.add_argument("--m", type=int, default=3, help="number of control outputs (U*)")
    p.add_argument("--div", type=int, default=12500, help="servo divider (125MHz / DIV)")
    p.add_argument("--scale", type=float, default=0.256, help="counts (256pm) -> nm scale")
    p.add_argument("--no-velocity", action="store_true", help="drop the velocity channel")
    p.add_argument("--no-uprev", action="store_true", help="drop the u_prev feedback block")
    p.add_argument("--setpoint", action="store_true", help="enable the reference feedforward (K_ff)")
    p.add_argument("--prev", action="store_true", help="add the previous-state block (x(k-1))")
    p.add_argument("--affine", action="store_true", help="add the affine/bias column")
    p.add_argument("--out-dir", default=None, help="write lqr.block.ini + lqr_block.vhd here")
    args = p.parse_args()

    c = Config(axes=args.axes, m=args.m, div=args.div, scale=args.scale,
               g_velocity=not args.no_velocity, g_uprev=not args.no_uprev,
               g_setpoint=args.setpoint, g_prev=args.prev, g_affine=args.affine)

    ini, vhd = make_block_ini(c), make_block_vhd(c)
    print("# %d axes, %d outputs, N=%d -> %d gains (table lines=%d, wr_addr=%d bits)%s"
          % (c.axes, c.m, state_width(c), gain_count(c), gain_count(c),
             max(1, (gain_count(c) - 1).bit_length()),
             ", setpoint ON" if c.g_setpoint else ""))

    if args.out_dir:
        import os
        os.makedirs(args.out_dir, exist_ok=True)
        with open(os.path.join(args.out_dir, "lqr.block.ini"), "w") as f:
            f.write(ini)
        with open(os.path.join(args.out_dir, "lqr_block.vhd"), "w") as f:
            f.write(vhd)
        print("# wrote lqr.block.ini + lqr_block.vhd to %s" % args.out_dir)
    else:
        print("\n===== lqr.block.ini =====\n" + ini)
        print("\n===== lqr_block.vhd =====\n" + vhd)


if __name__ == "__main__":
    main()
